version: '3.7'
services:
  prisma:
    container_name: prisma
    image: prismagraphql/prisma:1.22.0
    restart: always
    ports:
      - '${PRISMA_PORT}:${PRISMA_PORT}'
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_PORT}
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: ${PSQL_PORT}
            user: ${PSQL_USER}
            password: ${PSQL_PASSWORD}
            migrations: true

  postgres:
    container_name: postgres
    restart: always
    image: postgres:10.5
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    volumes:
      # if you are window user, currently it is impossible to mount psql storage to window drive, you can only use container storage https://github.com/docker/for-win/issues/445
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - '${PSQL_PORT}:5432'

volumes:
  postgres_volume:
    # persistent volume for psql
    name: ${DOCKER_VOLUME}
    external: true
