version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - run: echo "npm installing" # encho = printout
      - run: npm install
      - run: echo "npm run heroku-postbuild"
      - run: CI=true npm run heroku-postbuild # example:CI=true inject env variable CI = true
  test:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: echo "test-remote"
      - run: npm run test-remote
workflows:
  version: 2
  build_test_and_lint: # workflow name
    jobs:
      - build # run parallel
      - test # run parallel

