# circle ci env var is same as test.env
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing" # encho = printout
      - run: npm install
      - run: CI=true npm run build # example:CI=true inject env variable CI = true
  test:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm i
      - run: echo "jest-ci"
      - run: CI=true npm run jest-ci
workflows:
  version: 2
  build_test_and_lint: # workflow name
    jobs:
      - build # run parallel
      - test # run parallel
